import test from "node:test";
import assert from "node:assert/strict";

import {
    ExcalidrawParseError,
    convertExcalidraw,
    hexToRgb,
    parseExcalidraw,
} from "../parser.js";
import { SAMPLE_DATA } from "../sample-data.js";

function documentWith(elements) {
    return { type: "excalidraw", version: 2, elements };
}

test("parses the sample without mutating the source document", () => {
    const original = structuredClone(SAMPLE_DATA);
    const result = parseExcalidraw(SAMPLE_DATA);

    assert.equal(result.elements.length, 6);
    assert.deepEqual(result.diagnostics, []);
    assert.deepEqual(result.stats, {
        total: 6,
        converted: 6,
        skipped: 0,
        warnings: 0,
        errors: 0,
    });
    assert.deepEqual(SAMPLE_DATA, original);
});

test("converts supported elements to Asymptote commands", () => {
    const result = convertExcalidraw(SAMPLE_DATA);

    assert.match(result.code, /Generated by Cloud's Excalidraw to Asymptote/);
    assert.match(result.code, /filldraw\(/);
    assert.match(result.code, /ellipse\(/);
    assert.match(result.code, /arrow=Arrow\(TeXHead, size=10\)/);
    assert.match(result.code, /label\("Excalidraw → Asymptote"/);
    assert.equal(result.lineCount, 7);
});

test("reports unsupported and invalid elements without failing the whole document", () => {
    const result = convertExcalidraw(
        documentWith([
            { id: "unknown", type: "image", x: 0, y: 0 },
            null,
            {
                id: "line",
                type: "line",
                x: 0,
                y: 0,
                width: 10,
                height: 10,
                points: [
                    [0, 0],
                    [10, 10],
                ],
            },
        ]),
    );

    assert.equal(result.elements.length, 1);
    assert.equal(result.stats.skipped, 2);
    assert.equal(result.stats.warnings, 1);
    assert.equal(result.stats.errors, 1);
    assert.match(result.diagnostics[0].message, /image/);
    assert.match(result.code, /draw\(/);
});

test("reports malformed JSON clearly", () => {
    assert.throws(
        () => parseExcalidraw('{\n  "elements": [},\n}'),
        (error) => {
            assert.ok(error instanceof ExcalidrawParseError);
            assert.match(error.message, /Invalid JSON/);
            return true;
        },
    );
});

test("rejects documents without an elements array", () => {
    assert.throws(
        () => parseExcalidraw({ type: "excalidraw" }),
        /must contain an "elements" array/,
    );
});

test("uses valid Asymptote arrowbar expressions", () => {
    const startOnly = convertExcalidraw(
        documentWith([
            {
                type: "arrow",
                x: 0,
                y: 0,
                width: 10,
                height: 10,
                strokeColor: "#000000",
                points: [
                    [0, 0],
                    [10, 10],
                ],
                startArrowhead: "arrow",
            },
        ]),
    );
    const bothEnds = convertExcalidraw(
        documentWith([
            {
                type: "arrow",
                x: 0,
                y: 0,
                width: 10,
                height: 10,
                strokeColor: "#000000",
                points: [
                    [0, 0],
                    [10, 10],
                ],
                startArrowhead: "triangle",
                endArrowhead: "triangle",
            },
        ]),
    );

    assert.match(startOnly.code, /arrow=BeginArrow\(TeXHead, size=10\)/);
    assert.match(bothEnds.code, /arrow=ArcArrows\(DefaultHead, size=20\)/);
});

test("handles transparent strokes without emitting an invalid null pen", () => {
    const result = convertExcalidraw(
        documentWith([
            {
                id: "invisible",
                type: "rectangle",
                x: 0,
                y: 0,
                width: 20,
                height: 10,
                strokeColor: "transparent",
                backgroundColor: "transparent",
            },
        ]),
    );

    assert.doesNotMatch(result.code, /null/);
});

test("escapes text and converts colors consistently", () => {
    assert.equal(hexToRgb("#fff"), "rgb(1, 1, 1)");
    assert.equal(hexToRgb("#2563eb", false), "rgb(37, 99, 235)");

    const result = convertExcalidraw(
        documentWith([
            {
                id: "text",
                type: "text",
                x: 0,
                y: 0,
                width: 80,
                height: 20,
                text: 'a "quote"\\line',
                fontSize: 14,
                strokeColor: "#111827",
            },
        ]),
    );

    assert.match(result.code, /a \\"quote\\"\\\\line/);
});
