/**
 * Pure Excalidraw parsing and Asymptote generation.
 *
 * This module deliberately knows nothing about the DOM, canvas, or the page.
 * It accepts an Excalidraw JSON value (or its source text), returns normalized
 * drawing data, and returns diagnostics instead of writing to the console.
 */

export const SUPPORTED_TYPES = Object.freeze([
    "rectangle",
    "ellipse",
    "line",
    "arrow",
    "freedraw",
    "text",
]);

const SUPPORTED_TYPE_SET = new Set(SUPPORTED_TYPES);
const DEFAULT_STROKE = "#1e1e1e";
const DEFAULT_BACKGROUND = "transparent";
const DEFAULT_ARROWHEADS = {
    triangle: { kind: "arc", head: "DefaultHead", size: 20 },
    arrow: { kind: "standard", head: "TeXHead", size: 10 },
};
const HEADER = "/* Generated by Cloud's Excalidraw to Asymptote */";

export class ExcalidrawParseError extends Error {
    constructor(message, details = {}) {
        super(message);
        this.name = "ExcalidrawParseError";
        this.line = details.line;
        this.column = details.column;
        this.cause = details.cause;
    }
}

function finiteNumber(value, fallback = 0) {
    const number = typeof value === "number" ? value : Number(value);
    return Number.isFinite(number) ? number : fallback;
}

function clamp(value, min, max) {
    return Math.min(max, Math.max(min, value));
}

/** Round a number to a short, deterministic representation for generated code. */
export function toFixed(value, places = 0) {
    const numericValue = finiteNumber(value);
    const factor = 10 ** Math.max(0, places);
    const result = Math.round(numericValue * factor) / factor;
    return Object.is(result, -0) ? 0 : result;
}

export function formatNumber(value, places = 2) {
    const result = toFixed(value, places);
    return String(result);
}

function normalizeHex(value, fallback) {
    if (value === "transparent") return "transparent";

    const raw = String(value ?? "")
        .replace(/^#/, "")
        .trim();
    if (/^[0-9a-f]{3}$/i.test(raw)) {
        return `#${raw
            .split("")
            .map((character) => character + character)
            .join("")
            .toLowerCase()}`;
    }
    if (/^[0-9a-f]{6}$/i.test(raw)) {
        return `#${raw.toLowerCase()}`;
    }
    return fallback;
}

function colorChannels(hex) {
    const value = normalizeHex(hex, DEFAULT_STROKE).replace("#", "");
    return [
        Number.parseInt(value.slice(0, 2), 16),
        Number.parseInt(value.slice(2, 4), 16),
        Number.parseInt(value.slice(4, 6), 16),
    ];
}

/**
 * Convert a solid hex color to an Asymptote rgb() expression.
 * Transparent colors are returned unchanged.
 */
export function hexToRgb(hex, normalize = true) {
    const canonical = normalizeHex(hex, DEFAULT_STROKE);
    if (canonical === "transparent") return canonical;

    const channels = colorChannels(canonical);
    if (!normalize) return `rgb(${channels.join(", ")})`;

    return `rgb(${channels
        .map((channel) => formatNumber(toFixed(channel / 255, 2)))
        .join(", ")})`;
}

function isObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
}

function pointFrom(value) {
    if (Array.isArray(value) && value.length >= 2) {
        return [finiteNumber(value[0]), finiteNumber(value[1])];
    }
    return null;
}

function getPoints(rawElement) {
    if (!Array.isArray(rawElement.points)) return null;
    return rawElement.points.map(pointFrom).filter(Boolean);
}

function boundsForPoints(points) {
    if (!points.length) {
        return { minX: 0, minY: 0, maxX: 0, maxY: 0, width: 0, height: 0 };
    }

    let minX = points[0][0];
    let minY = points[0][1];
    let maxX = points[0][0];
    let maxY = points[0][1];

    for (const [x, y] of points.slice(1)) {
        minX = Math.min(minX, x);
        minY = Math.min(minY, y);
        maxX = Math.max(maxX, x);
        maxY = Math.max(maxY, y);
    }

    return {
        minX,
        minY,
        maxX,
        maxY,
        width: maxX - minX,
        height: maxY - minY,
    };
}

function rotatePoint(radians, center, point) {
    const deltaX = point[0] - center[0];
    const deltaY = point[1] - center[1];
    const cos = Math.cos(radians);
    const sin = Math.sin(radians);
    return [
        center[0] + deltaX * cos - deltaY * sin,
        center[1] + deltaX * sin + deltaY * cos,
    ];
}

function rectanglePoints(element) {
    const center = [
        element.x + element.width / 2,
        element.y + element.height / 2,
    ];
    const corners = [
        [element.x, element.y],
        [element.x + element.width, element.y],
        [element.x + element.width, element.y + element.height],
        [element.x, element.y + element.height],
    ];
    return corners.map((corner) => rotatePoint(element.angle, center, corner));
}

function linePoints(element) {
    const localPoints =
        element.localPoints.length >= 2
            ? element.localPoints
            : [
                  [0, 0],
                  [element.width, element.height],
              ];
    const localBounds = boundsForPoints(localPoints);
    const rotationCenter = [
        localBounds.minX + localBounds.width / 2,
        localBounds.minY + localBounds.height / 2,
    ];

    return localPoints.map((point) => {
        const rotated = rotatePoint(element.angle, rotationCenter, point);
        return [rotated[0] + element.x, rotated[1] + element.y];
    });
}

function normalizeElement(rawElement, index) {
    const type = rawElement.type;
    if (!SUPPORTED_TYPE_SET.has(type)) {
        throw new Error(`Unsupported element type "${type ?? "unknown"}".`);
    }

    const width = Math.abs(finiteNumber(rawElement.width));
    const height = Math.abs(finiteNumber(rawElement.height));
    const rawStroke = normalizeHex(rawElement.strokeColor, DEFAULT_STROKE);
    const rawBackground = normalizeHex(
        rawElement.backgroundColor,
        DEFAULT_BACKGROUND,
    );
    const strokeWidth = Math.max(0, finiteNumber(rawElement.strokeWidth, 1));
    const angle = finiteNumber(rawElement.angle);
    const opacity = clamp(finiteNumber(rawElement.opacity, 100) / 100, 0, 1);
    const roundness = rawElement.roundness ?? null;

    const element = {
        id: String(rawElement.id ?? `${type}-${index + 1}`),
        type,
        index,
        x: finiteNumber(rawElement.x),
        y: finiteNumber(rawElement.y),
        width,
        height,
        angle,
        opacity,
        roundness,
        strokeColor: rawStroke,
        strokeWidth: rawStroke === "transparent" ? 0 : strokeWidth,
        strokeStyle: rawElement.strokeStyle === "dashed" ? "dashed" : "solid",
        backgroundColor: rawBackground,
        filled: rawBackground !== "transparent",
        fillStyle:
            rawElement.fillStyle === "solid"
                ? "solid"
                : rawElement.fillStyle || "solid",
        localPoints: getPoints(rawElement) ?? [],
        startArrowhead: null,
        endArrowhead: null,
    };

    switch (type) {
        case "rectangle":
            element.points = rectanglePoints(element);
            break;
        case "line":
        case "arrow":
        case "freedraw":
            element.points = linePoints(element);
            if (type === "arrow") {
                element.startArrowhead =
                    DEFAULT_ARROWHEADS[rawElement.startArrowhead] ?? null;
                element.endArrowhead =
                    DEFAULT_ARROWHEADS[rawElement.endArrowhead] ?? null;
            }
            break;
        case "ellipse":
            element.center = [
                element.x + element.width / 2,
                element.y + element.height / 2,
            ];
            element.radius = [element.width / 2, element.height / 2];
            break;
        case "text":
            element.text = String(rawElement.text ?? "");
            element.fontSize = Math.max(
                1,
                finiteNumber(rawElement.fontSize, 16),
            );
            break;
        default:
            break;
    }

    return element;
}

function diagnostic(level, code, message, element, index) {
    return {
        level,
        code,
        message,
        elementId: element?.id ?? null,
        elementIndex: index,
        elementType: element?.type ?? null,
    };
}

function jsonErrorLocation(error, source) {
    const message = String(error?.message ?? "");
    const lineColumn = message.match(/line (\d+).*column (\d+)/i);
    if (lineColumn) {
        return { line: Number(lineColumn[1]), column: Number(lineColumn[2]) };
    }

    const match = message.match(/position (\d+)/i);
    if (!match) return {};
    const position = Number(match[1]);
    if (!Number.isInteger(position) || position < 0) return {};

    const before = source.slice(0, position);
    const line = before.split("\n").length;
    const lastNewline = before.lastIndexOf("\n");
    return {
        line,
        column: position - lastNewline,
    };
}

/** Parse JSON while preserving a source location when the runtime provides one. */
export function parseJsonSource(source) {
    const normalizedSource =
        typeof source === "string" ? source.replace(/^\uFEFF/, "") : source;
    try {
        return JSON.parse(normalizedSource);
    } catch (error) {
        const location = jsonErrorLocation(
            error,
            typeof normalizedSource === "string" ? normalizedSource : "",
        );
        const suffix = location.line
            ? ` at line ${location.line}, column ${location.column}`
            : "";
        throw new ExcalidrawParseError(
            `Invalid JSON${suffix}: ${error.message}`,
            {
                ...location,
                cause: error,
            },
        );
    }
}

/**
 * Normalize an Excalidraw document without touching the DOM.
 * Invalid individual elements are reported and skipped; malformed documents
 * reject the entire input.
 */
export function parseExcalidraw(source) {
    const document =
        typeof source === "string" ? parseJsonSource(source) : source;
    if (!isObject(document)) {
        throw new ExcalidrawParseError("Expected an Excalidraw JSON object.");
    }
    if (!Array.isArray(document.elements)) {
        throw new ExcalidrawParseError(
            'The JSON object must contain an "elements" array.',
        );
    }

    const diagnostics = [];
    const elements = [];

    document.elements.forEach((rawElement, index) => {
        if (!isObject(rawElement)) {
            diagnostics.push(
                diagnostic(
                    "error",
                    "invalid-element",
                    `Skipped element ${index + 1}: expected an object.`,
                    null,
                    index,
                ),
            );
            return;
        }

        if (!SUPPORTED_TYPE_SET.has(rawElement.type)) {
            const type = rawElement.type || "unknown";
            diagnostics.push(
                diagnostic(
                    "warning",
                    "unsupported-type",
                    `Skipped ${type} element #${index + 1}; this converter does not support it yet.`,
                    rawElement,
                    index,
                ),
            );
            return;
        }

        try {
            const element = normalizeElement(rawElement, index);
            elements.push(element);
            if (element.roundness !== null && element.type === "rectangle") {
                diagnostics.push(
                    diagnostic(
                        "warning",
                        "rounded-corners",
                        `Rounded corners on rectangle #${index + 1} were exported as sharp corners.`,
                        rawElement,
                        index,
                    ),
                );
            }
            if (element.filled && element.fillStyle !== "solid") {
                diagnostics.push(
                    diagnostic(
                        "warning",
                        "fill-style",
                        `Fill style "${element.fillStyle}" on element #${index + 1} was exported as a solid fill.`,
                        rawElement,
                        index,
                    ),
                );
            }
        } catch (error) {
            diagnostics.push(
                diagnostic(
                    "error",
                    "invalid-element",
                    `Skipped element #${index + 1}: ${error.message}`,
                    rawElement,
                    index,
                ),
            );
        }
    });

    return {
        elements,
        diagnostics,
        stats: {
            total: document.elements.length,
            converted: elements.length,
            skipped: document.elements.length - elements.length,
            warnings: diagnostics.filter((entry) => entry.level === "warning")
                .length,
            errors: diagnostics.filter((entry) => entry.level === "error")
                .length,
        },
    };
}

function penFor(element) {
    if (element.strokeColor === "transparent" || element.strokeWidth <= 0)
        return null;

    const parts = [
        hexToRgb(element.strokeColor),
        `linewidth(${formatNumber(element.strokeWidth)})`,
    ];
    if (element.strokeStyle === "dashed") parts.push("dashed");
    if (element.opacity < 1)
        parts.push(`opacity(${formatNumber(element.opacity)})`);
    return parts.join("+");
}

function fillCommand(path, element) {
    const color = hexToRgb(element.backgroundColor);
    const fillPen =
        element.opacity < 1
            ? `${color}+opacity(${formatNumber(element.opacity)})`
            : color;
    const pen = penFor(element);
    if (!pen) return `fill(${path}, ${fillPen});`;
    return `filldraw(${path}, ${fillPen}, ${pen});`;
}

function pathForPoints(points, closed = false, smooth = false) {
    if (!points.length) return "";
    const connector = smooth ? ".." : "--";
    const path = points
        .map(([x, y]) => `(${formatNumber(x)}, ${formatNumber(-y)})`)
        .join(connector);
    return closed ? `${path}--cycle` : path;
}

function arrowExpression(spec, position = "end") {
    const constructor =
        spec.kind === "arc"
            ? position === "start"
                ? "BeginArcArrow"
                : "ArcArrow"
            : position === "start"
              ? "BeginArrow"
              : "Arrow";
    return `${constructor}(${spec.head}, size=${formatNumber(spec.size)})`;
}

function arrowCommand(arrowheads) {
    const start = arrowheads.startArrowhead;
    const end = arrowheads.endArrowhead;
    if (start && end) {
        // Asymptote exposes ArcArrows/Arrows for two-ended arrows. If Excalidraw
        // supplies different heads, use the end head for both rather than emit an
        // invalid nested arrowbar expression.
        const both = end.kind === "arc" ? "ArcArrows" : "Arrows";
        return `arrow=${both}(${end.head}, size=${formatNumber(end.size)})`;
    }
    if (end) return `arrow=${arrowExpression(end)}`;
    if (start) return `arrow=${arrowExpression(start, "start")}`;
    return null;
}

function asymptoteForElement(element) {
    switch (element.type) {
        case "rectangle": {
            const path = pathForPoints(element.points, true);
            if (element.filled) return fillCommand(path, element);
            const pen = penFor(element);
            return pen ? `draw(${path}, ${pen});` : "";
        }
        case "ellipse": {
            const path = `shift(${formatNumber(element.center[0])}, ${formatNumber(-element.center[1])}) * rotate(${formatNumber((-element.angle * 180) / Math.PI)}) * ellipse((0, 0), ${formatNumber(element.radius[0])}, ${formatNumber(element.radius[1])})`;
            if (element.filled) return fillCommand(path, element);
            const pen = penFor(element);
            return pen ? `draw(${path}, ${pen});` : "";
        }
        case "line": {
            const path = pathForPoints(element.points, element.filled);
            if (element.filled) return fillCommand(path, element);
            const pen = penFor(element);
            return pen ? `draw(${path}, ${pen});` : "";
        }
        case "freedraw": {
            const path = pathForPoints(element.points, false, true);
            const pen = penFor(element);
            return pen ? `draw(${path}, ${pen});` : "";
        }
        case "arrow": {
            const path = pathForPoints(element.points, false, false);
            const pen = penFor(element);
            if (!pen) return "";
            const arrow = arrowCommand(element);
            return `draw(${path}, ${pen}${arrow ? `, ${arrow}` : ""});`;
        }
        case "text": {
            const centerX = element.x + element.width / 2;
            const centerY = element.y + element.height / 2;
            const pen = penFor(element);
            const rotation = formatNumber((-element.angle * 180) / Math.PI);
            const attributes = [
                `fontsize(${formatNumber(element.fontSize)}pt)`,
            ];
            if (pen) attributes.push(pen);
            return `shift(${formatNumber(centerX)}, ${formatNumber(-centerY)}) * rotate(${rotation}) * label(${escapeAsymptoteString(element.text)}, (0, 0), ${attributes.join(" + ")});`;
        }
        default:
            return "";
    }
}

function escapeAsymptoteString(value) {
    return `"${String(value)
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\r/g, "\\r")
        .replace(/\n/g, "\\n")
        .replace(/\t/g, "\\t")}"`;
}

/** Parse and convert a document in one pure operation. */
export function convertExcalidraw(source) {
    const result = parseExcalidraw(source);
    const snippets = result.elements.map(asymptoteForElement).filter(Boolean);
    const lineCount = snippets.length + 1; // Include the generated header.
    const code = `${HEADER}\n${snippets.length ? `${snippets.join("\n")}\n` : ""}`;

    return {
        ...result,
        code,
        lineCount,
        stats: {
            ...result.stats,
            outputLines: lineCount,
        },
    };
}
