/** A small, self-contained Excalidraw document for trying the converter. */
export const SAMPLE_DATA = {
    type: "excalidraw",
    version: 2,
    source: "https://excalidraw.com",
    elements: [
        {
            id: "rectangle-sample",
            type: "rectangle",
            x: 64,
            y: 56,
            width: 240,
            height: 128,
            angle: 0,
            strokeColor: "#2563eb",
            backgroundColor: "#dbeafe",
            fillStyle: "solid",
            strokeWidth: 3,
            strokeStyle: "solid",
            roundness: null,
            seed: 101,
            version: 1,
            versionNonce: 1,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
        {
            id: "ellipse-sample",
            type: "ellipse",
            x: 410,
            y: 54,
            width: 190,
            height: 132,
            angle: 0.08,
            strokeColor: "#db2777",
            backgroundColor: "#fce7f3",
            fillStyle: "solid",
            strokeWidth: 3,
            strokeStyle: "solid",
            roundness: null,
            seed: 102,
            version: 1,
            versionNonce: 2,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
        {
            id: "line-sample",
            type: "line",
            x: 92,
            y: 278,
            width: 490,
            height: 82,
            angle: 0,
            strokeColor: "#0f766e",
            backgroundColor: "transparent",
            fillStyle: "solid",
            strokeWidth: 3,
            strokeStyle: "solid",
            roundness: null,
            points: [
                [0, 0],
                [180, -12],
                [330, 38],
                [490, 82],
            ],
            seed: 103,
            version: 1,
            versionNonce: 3,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
        {
            id: "arrow-sample",
            type: "arrow",
            x: 138,
            y: 430,
            width: 360,
            height: -86,
            angle: 0,
            strokeColor: "#7c3aed",
            backgroundColor: "transparent",
            fillStyle: "solid",
            strokeWidth: 4,
            strokeStyle: "dashed",
            roundness: null,
            points: [
                [0, 0],
                [180, -28],
                [360, -86],
            ],
            startArrowhead: null,
            endArrowhead: "arrow",
            seed: 104,
            version: 1,
            versionNonce: 4,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
        {
            id: "freedraw-sample",
            type: "freedraw",
            x: 568,
            y: 310,
            width: 170,
            height: 108,
            angle: 0,
            strokeColor: "#ea580c",
            backgroundColor: "transparent",
            fillStyle: "solid",
            strokeWidth: 3,
            strokeStyle: "solid",
            roundness: null,
            points: [
                [0, 72],
                [22, 38],
                [49, 58],
                [75, 20],
                [104, 47],
                [132, 5],
                [170, 32],
            ],
            seed: 105,
            version: 1,
            versionNonce: 5,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
        {
            id: "text-sample",
            type: "text",
            x: 94,
            y: 548,
            width: 300,
            height: 34,
            angle: 0,
            strokeColor: "#111827",
            backgroundColor: "transparent",
            fillStyle: "solid",
            strokeWidth: 1,
            strokeStyle: "solid",
            roundness: null,
            text: "Excalidraw → Asymptote",
            fontSize: 24,
            fontFamily: 1,
            textAlign: "left",
            verticalAlign: "top",
            containerId: null,
            seed: 106,
            version: 1,
            versionNonce: 6,
            isDeleted: false,
            groupIds: [],
            boundElements: [],
            updated: 1,
            link: null,
            locked: false,
        },
    ],
    appState: {
        viewBackgroundColor: "#ffffff",
    },
    files: {},
};

export default SAMPLE_DATA;
